"""G2_F1_MAE01_20260829 — TEAM MAE01 driver (trial G00020).

Stage 1: per-trade MAE/MFE of P1/PCT's frozen 2,131 in-window trades at 1-min bar
resolution, with a bar-vs-tick calibration on ALLOWLIST_DEV_44 overlap sessions only.
Stage 2: the recorded 300-pt disaster stop, conservative intrabar ordering, frozen set,
preregistered decision rule applied verbatim.

The P1/PCT stream is regenerated by the VERBATIM recorded chain (identical calls to
runs/GENESIS_REPRO_INCUMBENT_20260828/src/repro_driver.py — direct imports, no
transcription) and cross-checked row-by-row against the frozen parity artifact
runs/WE_P1PCT_PARITY_20260827/out/py_trades_p1pct.csv. All ambiguity resolutions were
committed in out/spec_resolutions.txt BEFORE this ran (R1-R12, cited inline).

Writes ONLY to runs/G2_F1_MAE01_20260829/out/. Classification: RISK SPECIFICATION.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import time as _time

os.environ.setdefault("MPLBACKEND", "Agg")

import numpy as np
import pandas as pd

ROOT = r"D:\OneDrive - Washington University in St. Louis\TradingResearch\systematic_research"
RUN = os.path.join(ROOT, "runs", "G2_F1_MAE01_20260829")
OUT = os.path.join(RUN, "out")
os.makedirs(OUT, exist_ok=True)
SRC = os.path.join(ROOT, "research", "weekly_edge", "src")
sys.path.insert(0, SRC)
sys.path.insert(0, ROOT)

from research_sdk.seal_guard import assert_presealed                     # noqa: E402

T0 = _time.time()


def log(*a):
    print(f"[{_time.time()-T0:6.0f}s]", *a, flush=True)


log("importing recorded chain modules")
import run_we_w01 as W1                                                  # noqa: E402
from run_we_w01 import PV, COMM_RT                                       # noqa: E402
from run_we_w17 import load_deep                                         # noqa: E402
from run_we_w26 import fills_daily                                       # noqa: E402
from run_we_w37 import causal_score                                      # noqa: E402
from run_we_w39 import WIN                                               # noqa: E402
from run_we_w51 import session_frames                                    # noqa: E402
from run_we_w97 import votes                                             # noqa: E402
from run_we_w98 import gfills, arm_kw                                    # noqa: E402
from we_fastctx import fast_build_context                                # noqa: E402
from we_lab import spread_profile                                        # noqa: E402

A = np.datetime64("2022-07-01")
B = np.datetime64("2026-08-01")
SEAL = np.datetime64("2026-08-01")
TICKV = 5.0
STOP_PTS = 300.0            # FROZEN from the recorded risk menu — no other level touched
CALIB_MIN_TRADES = 10       # fixed in spec_resolutions.txt R5 BEFORE overlap was computed

ESNQ = os.path.join(ROOT, "research", "data_esnq")
ALLOWLIST_FILE = os.path.join(ESNQ, "ALLOWLIST_DEV_44.txt")
NQ_TICK_DIR = os.path.join(ESNQ, "parquet", "NQ")
NQ_MANIFEST = os.path.join(ESNQ, "raw", "NQ", "_manifest.csv")
PY_TRADES_ARTIFACT = os.path.join(ROOT, "runs", "WE_P1PCT_PARITY_20260827", "out",
                                  "py_trades_p1pct.csv")

CORE_INPUTS = [
    os.path.join(ROOT, "research", "scalping_lab", "substrate", "minute", "NQ",
                 "nq1m_2005_202605.parquet"),
    os.path.join(ROOT, "runs", "SM1M_SUBSTRATE", "out", "nq_1m_2022_2026.parquet"),
    os.path.join(ROOT, "runs", "WE_W76_FORWARD2026", "out", "mem_ext.npz"),
    os.path.join(ROOT, "runs", "WE_W82_FILLAUDIT", "out", "spread_by_minute.csv"),
    PY_TRADES_ARTIFACT,
    ALLOWLIST_FILE,
    NQ_MANIFEST,
]


def sha256_stream(path, chunk=1 << 22):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            b = f.read(chunk)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def qstats(v):
    """distribution stats in the native unit of v"""
    v = np.asarray(v, float)
    if len(v) == 0:
        return {k: np.nan for k in ("mean", "sd", "min", "p25", "p50", "p75", "p90",
                                    "p95", "p99", "max")}
    return dict(mean=float(v.mean()), sd=float(v.std(ddof=1)) if len(v) > 1 else 0.0,
                min=float(v.min()), p25=float(np.percentile(v, 25)),
                p50=float(np.percentile(v, 50)), p75=float(np.percentile(v, 75)),
                p90=float(np.percentile(v, 90)), p95=float(np.percentile(v, 95)),
                p99=float(np.percentile(v, 99)), max=float(v.max()))


def maxdd(curve):
    """max peak-to-trough drawdown of a cumulative equity curve (R8)"""
    peak = np.maximum.accumulate(curve)
    return float(np.max(peak - curve)) if len(curve) else 0.0


def main():
    prov = ["G2_F1_MAE01_20260829 — input provenance (printed by program)",
            f"python {sys.version.split()[0]}  numpy {np.__version__}  pandas {pd.__version__}"]
    for p in CORE_INPUTS:
        st = os.stat(p)
        prov.append(f"  {sha256_stream(p)}  {st.st_size:>12,} B  "
                    f"mtime {pd.Timestamp(st.st_mtime, unit='s').strftime('%Y-%m-%d %H:%M:%S')}  "
                    f"{os.path.relpath(p, ROOT)}")
        log("hashed", os.path.basename(p))
    prov.append("  (tick session parquets recorded below at open time as size+mtime; "
                "hashing ~40x200MB withheld for bounded runtime — stated, not hidden)")

    # ---------------------------------------------------------------- substrate + chain
    log("load_deep 2022-01-01 -> 2026-07-31 17:00 extend=True (verbatim repro chain)")
    prof = spread_profile()
    D = load_deep("2022-01-01", "2026-07-31 17:00", extend=True)
    W1.DEV_END = pd.Timestamp("2026-07-31").date()
    n, tarr, sid = D["n"], D["t"], D["sid"]
    o, c, h, l = D["o"], D["c"], D["h"], D["l"]
    assert_presealed(pd.DataFrame({"ts": pd.to_datetime(tarr)}), "ts",
                     "MAE01 substrate bar times")
    log(f"substrate bars {n:,} sessions {D['n_sess']:,}; seal_guard PASS on bar times")

    st_, en_, _ = session_frames(D)
    NSESS = D["n_sess"]
    win = np.array([A <= tarr[st_[s]] < B for s in range(NSESS)])
    sdate = pd.to_datetime(D["sess_date"])

    log("fast_build_context")
    X = fast_build_context(D)
    z = np.load(os.path.join(ROOT, "runs", "WE_W76_FORWARD2026", "out", "mem_ext.npz"))
    mem, bmom, tilt = z["mem"], z["bmom"], z["tilt"]
    if mem.shape[0] != n:
        raise SystemExit("mem_ext.npz rows != substrate bars — ABORT")

    def i_of(ts):
        return int(min(np.searchsorted(tarr, np.datetime64(ts)), n - 1))

    log("building P1_PCT (votes -> fills_daily -> causal_score -> gfills) — verbatim")
    vl, _ = votes(D, mem, bmom, tilt, X, bmom)
    p = vl.astype(np.int8)
    bb = fills_daily(D, p, halt=1300, target=1000)
    ee = np.array([i_of(x["et"]) for x in bb if A <= np.datetime64(x["et"]) < B])
    sc, _ = causal_score(X, ee, window=WIN)
    trP = gfills(D, p, np.where(sc >= 3, 2, 1).astype(np.int8), **arm_kw("PCT", 1.183))
    log(f"P1_PCT stream: {len(trP):,} total trades")

    # in-window by SESSION-START filter (R1)
    TR = [x for x in trP if win[int(sid[i_of(x["et"])])]]
    log(f"session-start in-window trades: {len(TR):,} (expect 2,131)")
    if len(TR) != 2131:
        raise SystemExit(f"POPULATION DEFECT: {len(TR)} != 2131 — ABORT, record defect")

    # cross-check vs frozen artifact (R1)
    PYA = pd.read_csv(PY_TRADES_ARTIFACT)
    assert_presealed(PYA, "et", "MAE01 frozen artifact et")
    assert_presealed(PYA, "xt", "MAE01 frozen artifact xt")
    mism = 0
    for i, x in enumerate(TR):
        r = PYA.iloc[i]
        okrow = (pd.Timestamp(x["et"]) == pd.Timestamp(r["et"])
                 and pd.Timestamp(x["xt"]) == pd.Timestamp(r["xt"])
                 and int(x["d"]) == int(r["d"]) and int(x["u"]) == int(r["u"])
                 and abs(round(x["pnl"], 2) - float(r["pnl"])) <= 0.005 + 1e-9)
        mism += 0 if okrow else 1
    log(f"artifact cross-check: {len(TR)-mism}/{len(TR)} rows identical "
        f"(et/xt/d/u exact, pnl to artifact 2-dp)")

    # ---------------------------------------------------------------- Stage 1: MAE/MFE
    log("Stage 1: reconstructing intervals + bar-extreme MAE/MFE (R2/R3)")
    rows = []
    n_unresolved = 0
    for i, x in enumerate(TR):
        ei, xi = i_of(x["et"]), i_of(x["xt"])
        ok = (str(tarr[ei]) == str(np.datetime64(x["et"]))
              and str(tarr[xi]) == str(np.datetime64(x["xt"])) and xi >= ei)
        d_, u_ = int(x["d"]), int(x["u"])
        epx = o[ei]
        exit_type = None
        if ok:
            px = epx + (x["pnl"] + COMM_RT * u_) / (d_ * u_ * PV)
            if abs(px - o[xi]) <= 1e-6 and xi > ei:
                exit_type = "OPEN"
            elif abs(px - c[xi]) <= 1e-6:
                exit_type = "CLOSE"
        if exit_type is None:
            n_unresolved += 1
            rows.append(dict(i=i, et=x["et"], xt=x["xt"], d=d_, u=u_, pnl=x["pnl"],
                             measured=0))
            continue
        if exit_type == "OPEN":
            lo = min(float(l[ei:xi].min()), float(o[xi]))
            hi = max(float(h[ei:xi].max()), float(o[xi]))
        else:
            lo = float(l[ei:xi + 1].min())
            hi = float(h[ei:xi + 1].max())
        if d_ > 0:
            mae = max(0.0, epx - lo); mfe = max(0.0, hi - epx)
        else:
            mae = max(0.0, hi - epx); mfe = max(0.0, epx - lo)
        rows.append(dict(i=i, et=x["et"], xt=x["xt"], d=d_, u=u_, pnl=x["pnl"],
                         measured=1, ei=ei, xi=xi, epx=epx, exit_type=exit_type,
                         exit_px=px, bars=(xi - ei), mae_pts=mae, mfe_pts=mfe,
                         mae_usd_ct=mae * PV, mfe_usd_ct=mfe * PV,
                         mae_usd_pos=mae * PV * u_, mfe_usd_pos=mfe * PV * u_,
                         outcome=("WIN" if x["pnl"] > 0 else "LOSS"),
                         sess_date=sdate[int(sid[ei])].strftime("%Y%m%d")))
    TDF = pd.DataFrame(rows)
    n_measured = int(TDF["measured"].sum())
    log(f"measured {n_measured}/{len(TR)} ({100.0*n_measured/len(TR):.2f}%), "
        f"unresolved {n_unresolved}, artifact mismatches {mism}")
    TDF.to_csv(os.path.join(OUT, "trade_mae_mfe.csv"), index=False)

    M = TDF[TDF.measured == 1]
    classes = [("ALL", M), ("WIN", M[M.outcome == "WIN"]), ("LOSS", M[M.outcome == "LOSS"]),
               ("U1", M[M.u == 1]), ("U2", M[M.u == 2]),
               ("WIN_U1", M[(M.outcome == "WIN") & (M.u == 1)]),
               ("WIN_U2", M[(M.outcome == "WIN") & (M.u == 2)]),
               ("LOSS_U1", M[(M.outcome == "LOSS") & (M.u == 1)]),
               ("LOSS_U2", M[(M.outcome == "LOSS") & (M.u == 2)])]
    drows = []
    for cname, cdf in classes:
        for metric, col in (("MAE", "mae_pts"), ("MFE", "mfe_pts")):
            s = qstats(cdf[col].to_numpy())
            row = dict(clazz=cname, metric=metric, n=len(cdf))
            row.update({f"{k}_pts": v for k, v in s.items()})
            row.update({f"{k}_usd_ct": (v * PV if np.isfinite(v) else v)
                        for k, v in s.items() if k in ("mean", "p50", "p90", "p95", "p99",
                                                       "max")})
            pos = cdf["mae_usd_pos" if metric == "MAE" else "mfe_usd_pos"].to_numpy()
            row["mean_usd_pos"] = float(pos.mean()) if len(pos) else np.nan
            row["max_usd_pos"] = float(pos.max()) if len(pos) else np.nan
            drows.append(row)
    DIST = pd.DataFrame(drows).rename(columns={"clazz": "class"})
    DIST.to_csv(os.path.join(OUT, "mae_mfe_distributions.csv"), index=False)
    log("mae_mfe_distributions.csv written")

    # ---------------------------------------------------------------- tick calibration
    log("tick calibration on ALLOWLIST_DEV_44 overlap (R5)")
    with open(ALLOWLIST_FILE) as f:
        allow = {ln.strip() for ln in f if ln.strip()}
    clines = []

    def C(*a):
        s = " ".join(str(x) for x in a)
        clines.append(s); print(s, flush=True)

    C("=" * 100)
    C("TICK CALIBRATION — ALLOWLIST ENFORCEMENT (printed per file, fail-closed)")
    C(f"allowlist file: {ALLOWLIST_FILE}")
    C(f"n_allowed = {len(allow)} (expect 44); policy: any tick read outside this list ABORTS")
    C("blind pools untouched: only research/data_esnq/parquet/NQ/s<allowlisted>.parquet opened")
    C("=" * 100)
    if len(allow) != 44:
        raise SystemExit("ALLOWLIST DEFECT: n_allowed != 44 — ABORT")
    man = pd.read_csv(NQ_MANIFEST).drop_duplicates(subset="session", keep="first")
    man = man.set_index("session")
    assert_presealed(man.reset_index(), "t_max", "MAE01 NQ manifest t_max")

    trade_sessions = sorted(set(M["sess_date"]))
    overlap_sessions = [s for s in trade_sessions
                        if s in allow and os.path.exists(
                            os.path.join(NQ_TICK_DIR, f"s{s}.parquet"))]
    n_overlap_trades_planned = int(M["sess_date"].isin(overlap_sessions).sum())
    C(f"trade sessions {len(trade_sessions)}; allowlisted overlap sessions "
      f"{len(overlap_sessions)}; overlapping measured trades {n_overlap_trades_planned}")
    calib = []
    calib_run = n_overlap_trades_planned >= CALIB_MIN_TRADES
    if not calib_run:
        C(f"overlap {n_overlap_trades_planned} < {CALIB_MIN_TRADES} (R5 threshold) — "
          f"calibration SKIPPED honestly; N reported (gate M2).")
    else:
        for sesskey in overlap_sessions:
            path = os.path.join(NQ_TICK_DIR, f"s{sesskey}.parquet")
            if sesskey not in allow:
                raise SystemExit(f"ALLOWLIST VIOLATION attempt: {sesskey} — ABORT")
            C(f"  ALLOWLIST ENFORCEMENT: s{sesskey} in ALLOWLIST_DEV_44 -> OK  ({path})")
            stt = os.stat(path)
            prov.append(f"  (tick) size {stt.st_size:>12,} B  mtime "
                        f"{pd.Timestamp(stt.st_mtime, unit='s').strftime('%Y-%m-%d %H:%M:%S')}"
                        f"  {os.path.relpath(path, ROOT)}")
            tk = pd.read_parquet(path, columns=["bip", "time", "price"])
            assert_presealed(tk, "time", f"MAE01 tick s{sesskey}")
            vc = tk["bip"].value_counts()
            want_trades = int(man.loc[f"s{sesskey}", "trades"]) \
                if f"s{sesskey}" in man.index else -1
            tb = [b for b in vc.index if int(vc[b]) == want_trades]
            if len(tb) == 1:
                trade_bip = int(tb[0])
            else:
                trade_bip = int(vc.idxmin())
                C(f"    WARN s{sesskey}: no unique bip count == manifest trades "
                  f"({want_trades}); using smallest-count bip {trade_bip} "
                  f"(counts {dict(vc)})")
            tt = tk[tk.bip == trade_bip]
            times = tt["time"].to_numpy()
            prices = tt["price"].to_numpy()
            del tk, tt
            sub = M[M.sess_date == sesskey]
            offs = []
            for _, r in sub.iterrows():
                t_ent = np.datetime64(r["et"]) - np.timedelta64(60, "s")
                i0 = int(np.searchsorted(times, t_ent, side="left"))
                if i0 >= len(times):
                    continue
                if r["exit_type"] == "OPEN":
                    t_end = np.datetime64(r["xt"]) - np.timedelta64(60, "s")
                    i1 = int(np.searchsorted(times, t_end, side="left"))
                    sl = prices[i0:i1]
                    extra = prices[i1] if i1 < len(prices) else None
                    if extra is not None:
                        sl = np.concatenate([sl, [extra]])
                else:
                    t_end = np.datetime64(r["xt"])
                    i1 = int(np.searchsorted(times, t_end, side="left"))
                    sl = prices[i0:i1]
                if len(sl) == 0:
                    continue
                epx_t = float(prices[i0])
                lo_t, hi_t = float(sl.min()), float(sl.max())
                if r["d"] > 0:
                    mae_t = max(0.0, epx_t - lo_t); mfe_t = max(0.0, hi_t - epx_t)
                else:
                    mae_t = max(0.0, hi_t - epx_t); mfe_t = max(0.0, epx_t - lo_t)
                offs.append(float(r["epx"]) - epx_t)
                calib.append(dict(sess=sesskey, i=int(r["i"]), d=int(r["d"]),
                                  mae_bar=float(r["mae_pts"]), mae_tick=mae_t,
                                  mfe_bar=float(r["mfe_pts"]), mfe_tick=mfe_t,
                                  epx_off=float(r["epx"]) - epx_t))
            if offs:
                C(f"    s{sesskey}: {len(offs)} trades; bar-vs-tick entry offset "
                  f"median {np.median(offs):+.2f} pts (adjustment diagnostic)")
    CAL = pd.DataFrame(calib)
    n_calib = len(CAL)
    if calib_run and n_calib > 0:
        f_mae = float(CAL.mae_tick.mean() / max(CAL.mae_bar.mean(), 1e-12))
        f_mfe = float(CAL.mfe_tick.mean() / max(CAL.mfe_bar.mean(), 1e-12))
        d_mae = float((CAL.mae_tick - CAL.mae_bar).mean())
        d_mfe = float((CAL.mfe_tick - CAL.mfe_bar).mean())
        C("")
        C(f"CALIBRATION FACTOR (reported, applied to NOTHING — R5):")
        C(f"  N = {n_calib} trades on {CAL.sess.nunique()} allowlisted dev sessions")
        C(f"  MAE: mean tick/bar ratio {f_mae:.4f}; mean paired diff (tick-bar) "
          f"{d_mae:+.3f} pts; |diff| p95 {np.percentile(np.abs(CAL.mae_tick-CAL.mae_bar),95):.3f} pts")
        C(f"  MFE: mean tick/bar ratio {f_mfe:.4f}; mean paired diff (tick-bar) "
          f"{d_mfe:+.3f} pts; |diff| p95 {np.percentile(np.abs(CAL.mfe_tick-CAL.mfe_bar),95):.3f} pts")
        C("  Stage 1 tables remain BAR-BASED; nothing was silently (or otherwise) adjusted.")
        CAL.to_csv(os.path.join(OUT, "calibration_trades.csv"), index=False)
    else:
        f_mae = f_mfe = d_mae = d_mfe = float("nan")
        if calib_run:
            C("calibration produced 0 usable trades — reported and skipped.")
    with open(os.path.join(OUT, "calibration.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(clines) + "\n")

    # ---------------------------------------------------------------- Stage 2: 300pt stop
    log("Stage 2: 300pt disaster stop overlay (R6-R8), frozen set, conservative ordering")
    rate_w = {}
    for x in TR:
        for ts in (x["et"], x["xt"]):
            p_ = pd.Timestamp(ts); m2 = p_.hour * 60 + p_.minute
            rate_w[m2] = rate_w.get(m2, 0.0) + x["u"]
    rate_base = TICKV * sum(float(prof.get(m2, 3.0)) * q for m2, q in rate_w.items()) / \
        max(sum(rate_w.values()), 1e-9)

    stop_rows = []
    new_pnl = []
    new_xt = []
    n_trig = 0
    for _, r in TDF.iterrows():
        if r["measured"] != 1:
            new_pnl.append(r["pnl"]); new_xt.append(r["xt"])
            continue
        ei, xi = int(r["ei"]), int(r["xi"])
        d_, u_, epx = int(r["d"]), int(r["u"]), float(r["epx"])
        jhi = xi if r["exit_type"] == "CLOSE" else xi - 1
        lvl = epx - STOP_PTS if d_ > 0 else epx + STOP_PTS
        trig_j = -1
        if jhi >= ei:
            seg = l[ei:jhi + 1] if d_ > 0 else h[ei:jhi + 1]
            hitmask = (seg <= lvl) if d_ > 0 else (seg >= lvl)
            if hitmask.any():
                trig_j = ei + int(np.argmax(hitmask))
        if trig_j < 0:
            new_pnl.append(r["pnl"]); new_xt.append(r["xt"])
            continue
        n_trig += 1
        fill = min(lvl, o[trig_j]) if d_ > 0 else max(lvl, o[trig_j])
        pnl2 = d_ * u_ * (fill - epx) * PV - COMM_RT * u_
        new_pnl.append(pnl2); new_xt.append(str(tarr[trig_j]))
        stop_rows.append(dict(et=r["et"], d=d_, u=u_, exit_type=r["exit_type"],
                              frozen_pnl=float(r["pnl"]), stop_pnl=float(pnl2),
                              delta=float(pnl2 - r["pnl"]), fill=float(fill),
                              stop_bar=str(tarr[trig_j]), mae_pts=float(r["mae_pts"])))

    rate_w2 = {}
    for x, xt2 in zip(TR, new_xt):
        for ts in (x["et"], xt2):
            p_ = pd.Timestamp(ts); m2 = p_.hour * 60 + p_.minute
            rate_w2[m2] = rate_w2.get(m2, 0.0) + x["u"]
    rate_stop = TICKV * sum(float(prof.get(m2, 3.0)) * q for m2, q in rate_w2.items()) / \
        max(sum(rate_w2.values()), 1e-9)

    us = np.array([x["u"] for x in TR], float)
    pnl_base = np.array([x["pnl"] for x in TR], float)
    pnl_stop = np.array(new_pnl, float)
    net_base_tr = pnl_base - rate_base * us
    net_stop_tr = pnl_stop - rate_stop * us
    net_base, net_stop = float(net_base_tr.sum()), float(net_stop_tr.sum())
    gross_base, gross_stop = float(pnl_base.sum()), float(pnl_stop.sum())
    gross_pos = float(pnl_base[pnl_base > 0].sum())
    dd_base = maxdd(np.cumsum(net_base_tr))
    dd_stop = maxdd(np.cumsum(net_stop_tr))
    delta_net = net_stop - net_base
    if net_base <= 0:
        raise SystemExit("DEFECT: baseline total net <= 0 — decision clause denominator invalid")
    clause1 = delta_net >= -0.01 * net_base
    dd_improve = (dd_base - dd_stop) / max(dd_base, 1e-9)
    clause2 = dd_improve >= 0.10
    adopt = clause1 and clause2

    slines = []

    def S(*a):
        s = " ".join(str(x) for x in a)
        slines.append(s); print(s, flush=True)

    S("=" * 100)
    S("STAGE 2 — 300 pt DISASTER STOP ON THE FROZEN P1/PCT SET (trial G00020; RISK SPECIFICATION)")
    S("variant frozen from the recorded risk menu; conservative intrabar ordering: stop checked")
    S("before favorable exit within a bar; fill = worse-of(level, bar open). No other change:")
    S("all other trades / entries / session-box sequence stay FROZEN (overlay limitation, R6).")
    S("=" * 100)
    S(f"trades evaluated                : {len(TR):,} (measured {n_measured:,})")
    S(f"stop triggers                   : {n_trig}  (W-era testimony: 13 — re-measured here)")
    S(f"baseline gross (stored pnl)     : $ {gross_base:>12,.2f}")
    S(f"variant  gross                  : $ {gross_stop:>12,.2f}   delta $ {gross_stop-gross_base:>+10,.2f}")
    S(f"  delta gross as % of baseline gross total     : {100*(gross_stop-gross_base)/gross_base:+.3f} %")
    S(f"  delta gross as % of baseline gross positives : {100*(gross_stop-gross_base)/gross_pos:+.3f} %"
      f"   (testimony said ~0.7% of gross)")
    S(f"spread rate $/ctrRT             : baseline {rate_base:.4f}  variant {rate_stop:.4f} (recomputed, R7)")
    S(f"baseline total NET              : $ {net_base:>12,.2f}")
    S(f"variant  total NET              : $ {net_stop:>12,.2f}")
    S(f"delta net                       : $ {delta_net:>+12,.2f}  = {100*delta_net/net_base:+.3f} % of total net")
    S(f"trade-level maxDD (net, R8)     : baseline $ {dd_base:,.2f}  variant $ {dd_stop:,.2f}")
    S(f"maxDD improvement               : {100*dd_improve:+.2f} %  (clause requires >= +10 %)")
    S("")
    if stop_rows:
        S("triggered trades (all listed):")
        S(f"{'entry':<21}{'d':>3}{'u':>3}{'type':>6}{'frozen pnl':>13}{'stop pnl':>13}"
          f"{'delta':>11}{'MAE pts':>9}")
        for sr in stop_rows:
            S(f"{sr['et']:<21}{sr['d']:>3}{sr['u']:>3}{sr['exit_type']:>6}"
              f"{sr['frozen_pnl']:>13,.2f}{sr['stop_pnl']:>13,.2f}{sr['delta']:>11,.2f}"
              f"{sr['mae_pts']:>9.1f}")
        pd.DataFrame(stop_rows).to_csv(os.path.join(OUT, "stop300_triggers.csv"), index=False)
    else:
        S("triggered trades: NONE")
    S("")
    S("DECISION RULE (preregistered, applied VERBATIM):")
    S('  "recommend ADOPT-FOR-CERTIFICATION only if (delta net >= -1% of total net) AND')
    S('   (trade-level maxDD improves >= 10%); otherwise RECORD AND STOP. Any adoption')
    S('   invalidates Standard-fill parity and requires re-certification (LIVE_READINESS.md:163)"')
    S(f"  clause 1: delta net {delta_net:+,.2f} >= -1% of total net ({-0.01*net_base:,.2f})"
      f"  -> {'PASS' if clause1 else 'FAIL'}")
    S(f"  clause 2: trade-level maxDD improvement {100*dd_improve:+.2f} % >= 10 %"
      f"  -> {'PASS' if clause2 else 'FAIL'}")
    S(f"  RECOMMENDATION: {'ADOPT-FOR-CERTIFICATION' if adopt else 'RECORD AND STOP'}")
    S("  NOTE (printed per spec): any adoption invalidates Standard-fill parity and requires")
    S("  re-certification (LIVE_READINESS.md:163).")
    with open(os.path.join(OUT, "stop300_impact.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(slines) + "\n")
    log("stop300_impact.txt written")

    # ---------------------------------------------------------------- gate table
    glines = []

    def G(*a):
        s = " ".join(str(x) for x in a)
        glines.append(s); print(s, flush=True)

    # M1 per R1: artifact mismatches count against measured
    n_meas_eff = max(0, n_measured - mism)
    m1 = (100.0 * n_meas_eff / len(TR)) >= 95.0
    m1_obs = f"{n_measured}/{len(TR)} = {100.0*n_measured/len(TR):.2f}% measured; " \
             f"artifact mismatches {mism} (effective {n_meas_eff})"
    m2 = True  # N reported by construction (printed above and here)
    m2_obs = (f"overlap N: {n_calib} trades / "
              f"{CAL.sess.nunique() if n_calib else 0} sessions; "
              + (f"calibration RUN (factors MAE {f_mae:.4f} / MFE {f_mfe:.4f})"
                 if calib_run and n_calib > 0 else "calibration SKIPPED (N < 10, R5)"))
    m3 = True  # rule applied verbatim above; both clauses evaluated and printed
    m3_obs = (f"clause1 {'PASS' if clause1 else 'FAIL'}, clause2 "
              f"{'PASS' if clause2 else 'FAIL'} -> "
              f"{'ADOPT-FOR-CERTIFICATION' if adopt else 'RECORD AND STOP'}")

    G("=" * 110)
    G("G2_F1_MAE01_20260829 — GATE TABLE (printed by program)")
    G("=" * 110)
    G(f"{'GATE':<6}{'SPEC':<56}{'OBSERVED':<74}{'PASS/FAIL'}")
    G(f"{'M1':<6}{'measurement completeness >= 95% of 2,131 trades':<56}{m1_obs:<74}"
      f"{'PASS' if m1 else 'FAIL'}")
    G(f"{'M2':<6}{'calibration overlap N reported (allowlist only)':<56}{m2_obs:<74}"
      f"{'PASS' if m2 else 'FAIL'}")
    G(f"{'M3':<6}{'decision rule applied verbatim':<56}{m3_obs:<74}"
      f"{'PASS' if m3 else 'FAIL'}")
    G("-" * 110)
    G("seal enforcement: seal_guard.assert_presealed PASS on substrate bar times, artifact")
    G(f"et/xt, manifest t_max, and every tick file opened ({CAL.sess.nunique() if n_calib else 0}"
      f" sessions); no value >= 2026-08-01 read or persisted.")
    G("allowlist enforcement: printed per file in out/calibration.txt; ALLOWLIST_DEV_44 only;")
    G("blind pools untouched.")
    G("prohibitions honored: single stop level 300 (frozen), no target/trailing variants, no")
    G("grid, no alpha language — classification RISK SPECIFICATION.")
    G("MDE: not requested by the spec's gate list; both stages are deterministic measurements")
    G("on a frozen trade set (no sampling inference) — stated per R9 before the verdict.")
    overall = m1 and m2 and m3
    G(f"OVERALL: {'PASS' if overall else 'FAIL'}   recommendation: "
      f"{'ADOPT-FOR-CERTIFICATION' if adopt else 'RECORD AND STOP'}")
    G("")
    G("headline Stage 1 figures (bar-based, per contract, ALL class):")
    sa = qstats(M["mae_pts"].to_numpy()); sf = qstats(M["mfe_pts"].to_numpy())
    G(f"  MAE pts: p50 {sa['p50']:.2f}  p90 {sa['p90']:.2f}  p95 {sa['p95']:.2f}  "
      f"p99 {sa['p99']:.2f}  max {sa['max']:.2f} (= $ {sa['max']*PV:,.0f}/ct)")
    G(f"  MFE pts: p50 {sf['p50']:.2f}  p90 {sf['p90']:.2f}  p95 {sf['p95']:.2f}  "
      f"p99 {sf['p99']:.2f}  max {sf['max']:.2f}")
    try:
        import psutil
        peak = psutil.Process().memory_info().peak_wset / 1e9
        G(f"peak working set: {peak:.2f} GB")
    except Exception:
        peak = None
    wall = _time.time() - T0
    G(f"wall time: {wall:.0f} s")
    with open(os.path.join(OUT, "gate_table.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(glines) + "\n")

    with open(os.path.join(OUT, "run_provenance.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(prov) + f"\nwall_s {wall:.0f}\npeak_gb "
                f"{peak if peak is not None else 'n/a'}\n")

    result = {
        "trial_id": "G00020",
        "metrics": {
            "n_trades": len(TR), "n_measured": n_measured,
            "pct_measured": round(100.0 * n_measured / len(TR), 2),
            "artifact_mismatches": mism,
            "mae_p50_pts": round(sa["p50"], 2), "mae_p95_pts": round(sa["p95"], 2),
            "mae_p99_pts": round(sa["p99"], 2), "mae_max_pts": round(sa["max"], 2),
            "mae_max_usd_per_ct": round(sa["max"] * PV, 2),
            "mfe_p50_pts": round(sf["p50"], 2), "mfe_p95_pts": round(sf["p95"], 2),
            "calib_n_trades": n_calib,
            "calib_n_sessions": int(CAL.sess.nunique()) if n_calib else 0,
            "calib_factor_mae": None if not np.isfinite(f_mae) else round(f_mae, 4),
            "calib_factor_mfe": None if not np.isfinite(f_mfe) else round(f_mfe, 4),
            "stop300_triggers": n_trig,
            "net_base": round(net_base, 2), "net_stop": round(net_stop, 2),
            "delta_net": round(delta_net, 2),
            "delta_net_pct_of_net": round(100 * delta_net / net_base, 3),
            "delta_gross_pct_of_gross_pos": round(100 * (gross_stop - gross_base) / gross_pos, 3),
            "maxdd_trade_base": round(dd_base, 2), "maxdd_trade_stop": round(dd_stop, 2),
            "maxdd_improve_pct": round(100 * dd_improve, 2),
            "clause1": bool(clause1), "clause2": bool(clause2),
            "m1": bool(m1), "m2": bool(m2), "m3": bool(m3),
            "wall_s": round(wall),
        },
        "result": "PASS" if overall else "FAIL",
        "note": ("MAE/MFE measured at 1-min bar extremes on the frozen 2,131 P1/PCT trades "
                 "(RISK SPECIFICATION, no alpha claim); tick calibration on ALLOWLIST_DEV_44 "
                 "overlap reported, applied to nothing; 300pt disaster stop (frozen level) "
                 f"triggered {n_trig}x, decision rule verbatim -> "
                 + ("ADOPT-FOR-CERTIFICATION (would invalidate Standard-fill parity; "
                    "re-certification required, LIVE_READINESS.md:163)." if adopt
                    else "RECORD AND STOP.")),
    }
    with open(os.path.join(OUT, "ledger_result_pending.json"), "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    log("ledger_result_pending.json written —", result["result"])


if __name__ == "__main__":
    main()
